# PostgreSQL. Versions 9.1 and up are supported.
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  min_messages: notice

test:
  <<: *default
  database: rails5-authlogic-tutorial_test

# Production settings in .env.production
production:
  <<: *default
